matrix:
  include:
    # OSX 10.10 Yosemite
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode7
      language: generic
    - os: osx
      osx_image: xcode7.1
      language: generic
    # OSX 10.11 El Capitan
    - os: osx
      osx_image: xcode7.2
      language: generic
    - os: osx
      osx_image: xcode7.3
      language: generic
    # macOS 10.12 Sierra
    - os: osx
      osx_image: xcode8
      language: generic
install:
  - brew install python3
  - make -f Makefile
script:
  - export DYLD_LIBRARY_PATH=`pwd`/tests/objc
  - python3 setup.py test
