language: python
python: 2.7
env:
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=pypy
install:
  - pip install tox
  - make
script:
  - export LD_LIBRARY_PATH=`pwd`/tests/objc
  - tox -e $TOX_ENV

